/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as VerifyEmailRouteImport } from "./pages/verify-email"
import { Route as UnauthorizedRouteImport } from "./pages/unauthorized"
import { Route as SignupRouteImport } from "./pages/signup"
import { Route as SignInRouteImport } from "./pages/sign-in"
import { Route as ResetPasswordRouteImport } from "./pages/reset-password"
import { Route as LoadingDemoRouteImport } from "./pages/loading-demo"
import { Route as ForgotPasswordRouteImport } from "./pages/forgot-password"
import { Route as AppRouteImport } from "./pages/_app"
import { Route as R500RouteImport } from "./pages/500"
import { Route as R404RouteImport } from "./pages/404"
import { Route as AppIndexRouteImport } from "./pages/_app/index"
import { Route as InviteTokenRouteImport } from "./pages/invite.$token"
import { Route as AppTeamRouteImport } from "./pages/_app/team"
import { Route as AppOrganizationsRouteImport } from "./pages/_app/organizations"
import { Route as AppBillingRouteImport } from "./pages/_app/billing"
import { Route as AppAccountRouteImport } from "./pages/_app/account"

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: "/unauthorized",
  path: "/unauthorized",
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingDemoRoute = LoadingDemoRouteImport.update({
  id: "/loading-demo",
  path: "/loading-demo",
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: "/500",
  path: "/500",
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: "/404",
  path: "/404",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: "/invite/$token",
  path: "/invite/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: "/team",
  path: "/team",
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: "/organizations",
  path: "/organizations",
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  "/404": typeof R404Route
  "/500": typeof R500Route
  "/": typeof AppIndexRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/loading-demo": typeof LoadingDemoRoute
  "/reset-password": typeof ResetPasswordRoute
  "/sign-in": typeof SignInRoute
  "/signup": typeof SignupRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/verify-email": typeof VerifyEmailRoute
  "/account": typeof AppAccountRoute
  "/billing": typeof AppBillingRoute
  "/organizations": typeof AppOrganizationsRoute
  "/team": typeof AppTeamRoute
  "/invite/$token": typeof InviteTokenRoute
}
export interface FileRoutesByTo {
  "/404": typeof R404Route
  "/500": typeof R500Route
  "/forgot-password": typeof ForgotPasswordRoute
  "/loading-demo": typeof LoadingDemoRoute
  "/reset-password": typeof ResetPasswordRoute
  "/sign-in": typeof SignInRoute
  "/signup": typeof SignupRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/verify-email": typeof VerifyEmailRoute
  "/account": typeof AppAccountRoute
  "/billing": typeof AppBillingRoute
  "/organizations": typeof AppOrganizationsRoute
  "/team": typeof AppTeamRoute
  "/invite/$token": typeof InviteTokenRoute
  "/": typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/404": typeof R404Route
  "/500": typeof R500Route
  "/_app": typeof AppRouteWithChildren
  "/forgot-password": typeof ForgotPasswordRoute
  "/loading-demo": typeof LoadingDemoRoute
  "/reset-password": typeof ResetPasswordRoute
  "/sign-in": typeof SignInRoute
  "/signup": typeof SignupRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/verify-email": typeof VerifyEmailRoute
  "/_app/account": typeof AppAccountRoute
  "/_app/billing": typeof AppBillingRoute
  "/_app/organizations": typeof AppOrganizationsRoute
  "/_app/team": typeof AppTeamRoute
  "/invite/$token": typeof InviteTokenRoute
  "/_app/": typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/404"
    | "/500"
    | "/"
    | "/forgot-password"
    | "/loading-demo"
    | "/reset-password"
    | "/sign-in"
    | "/signup"
    | "/unauthorized"
    | "/verify-email"
    | "/account"
    | "/billing"
    | "/organizations"
    | "/team"
    | "/invite/$token"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/404"
    | "/500"
    | "/forgot-password"
    | "/loading-demo"
    | "/reset-password"
    | "/sign-in"
    | "/signup"
    | "/unauthorized"
    | "/verify-email"
    | "/account"
    | "/billing"
    | "/organizations"
    | "/team"
    | "/invite/$token"
    | "/"
  id:
    | "__root__"
    | "/404"
    | "/500"
    | "/_app"
    | "/forgot-password"
    | "/loading-demo"
    | "/reset-password"
    | "/sign-in"
    | "/signup"
    | "/unauthorized"
    | "/verify-email"
    | "/_app/account"
    | "/_app/billing"
    | "/_app/organizations"
    | "/_app/team"
    | "/invite/$token"
    | "/_app/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoadingDemoRoute: typeof LoadingDemoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify-email": {
      id: "/verify-email"
      path: "/verify-email"
      fullPath: "/verify-email"
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/unauthorized": {
      id: "/unauthorized"
      path: "/unauthorized"
      fullPath: "/unauthorized"
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/signup": {
      id: "/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sign-in": {
      id: "/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password": {
      id: "/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/loading-demo": {
      id: "/loading-demo"
      path: "/loading-demo"
      fullPath: "/loading-demo"
      preLoaderRoute: typeof LoadingDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forgot-password": {
      id: "/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/500": {
      id: "/500"
      path: "/500"
      fullPath: "/500"
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/404": {
      id: "/404"
      path: "/404"
      fullPath: "/404"
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/invite/$token": {
      id: "/invite/$token"
      path: "/invite/$token"
      fullPath: "/invite/$token"
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/team": {
      id: "/_app/team"
      path: "/team"
      fullPath: "/team"
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/organizations": {
      id: "/_app/organizations"
      path: "/organizations"
      fullPath: "/organizations"
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/billing": {
      id: "/_app/billing"
      path: "/billing"
      fullPath: "/billing"
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/account": {
      id: "/_app/account"
      path: "/account"
      fullPath: "/account"
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppBillingRoute: typeof AppBillingRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppBillingRoute: AppBillingRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404Route,
  R500Route: R500Route,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoadingDemoRoute: LoadingDemoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
