/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as R404RouteImport } from "./pages/404"
import { Route as R500RouteImport } from "./pages/500"
import { Route as AppRouteImport } from "./pages/_app"
import { Route as CompleteProfileRouteImport } from "./pages/complete-profile"
import { Route as CreateOrganizationRouteImport } from "./pages/create-organization"
import { Route as ForgotPasswordRouteImport } from "./pages/forgot-password"
import { Route as LoadingDemoRouteImport } from "./pages/loading-demo"
import { Route as MagicLinkRouteImport } from "./pages/magic-link"
import { Route as ResetPasswordRouteImport } from "./pages/reset-password"
import { Route as SignInRouteImport } from "./pages/sign-in"
import { Route as SignupRouteImport } from "./pages/signup"
import { Route as UnauthorizedRouteImport } from "./pages/unauthorized"
import { Route as VerifyEmailRouteImport } from "./pages/verify-email"
import { Route as AppIndexRouteImport } from "./pages/_app/index"
import { Route as AppAddonsRouteImport } from "./pages/_app/addons"
import { Route as AppCmsPagesRouteImport } from "./pages/_app/cms-pages"
import { Route as AppTeamRouteImport } from "./pages/_app/team"
import { Route as AuthCallbackRouteImport } from "./pages/auth.callback"
import { Route as InviteTokenRouteImport } from "./pages/invite.$token"
import { Route as MagicLinkIndexRouteImport } from "./pages/magic-link.index"
import { Route as MagicLinkVerifyRouteImport } from "./pages/magic-link.verify"
import { Route as AppAddonsAddonPathRouteImport } from "./pages/_app/addons/$addonPath"
import { Route as AppBillingIndexRouteImport } from "./pages/_app/billing/index"
import { Route as AppBillingFailureRouteImport } from "./pages/_app/billing/failure"
import { Route as AppBillingSuccessRouteImport } from "./pages/_app/billing/success"
import { Route as AppCmsPagesIndexRouteImport } from "./pages/_app/cms-pages.index"
import { Route as AppCmsPagesPageIdRouteImport } from "./pages/_app/cms-pages.$pageId"
import { Route as AppCmsPagesCreateRouteImport } from "./pages/_app/cms-pages.create"
import { Route as AppSettingsGeneralRouteImport } from "./pages/_app/settings/general"
import { Route as AppSettingsNotificationsRouteImport } from "./pages/_app/settings/notifications"
import { Route as AppSettingsOrganizationRouteImport } from "./pages/_app/settings/organization"
import { Route as AppSettingsSecurityRouteImport } from "./pages/_app/settings/security"

const R404Route = R404RouteImport.update({
  id: "/404",
  path: "/404",
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: "/500",
  path: "/500",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: "/complete-profile",
  path: "/complete-profile",
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: "/create-organization",
  path: "/create-organization",
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingDemoRoute = LoadingDemoRouteImport.update({
  id: "/loading-demo",
  path: "/loading-demo",
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkRoute = MagicLinkRouteImport.update({
  id: "/magic-link",
  path: "/magic-link",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: "/unauthorized",
  path: "/unauthorized",
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any)
const AppAddonsRoute = AppAddonsRouteImport.update({
  id: "/addons",
  path: "/addons",
  getParentRoute: () => AppRoute,
} as any)
const AppCmsPagesRoute = AppCmsPagesRouteImport.update({
  id: "/cms-pages",
  path: "/cms-pages",
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: "/team",
  path: "/team",
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: "/invite/$token",
  path: "/invite/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkIndexRoute = MagicLinkIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MagicLinkRoute,
} as any)
const MagicLinkVerifyRoute = MagicLinkVerifyRouteImport.update({
  id: "/verify",
  path: "/verify",
  getParentRoute: () => MagicLinkRoute,
} as any)
const AppAddonsAddonPathRoute = AppAddonsAddonPathRouteImport.update({
  id: "/$addonPath",
  path: "/$addonPath",
  getParentRoute: () => AppAddonsRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: "/billing/",
  path: "/billing/",
  getParentRoute: () => AppRoute,
} as any)
const AppBillingFailureRoute = AppBillingFailureRouteImport.update({
  id: "/billing/failure",
  path: "/billing/failure",
  getParentRoute: () => AppRoute,
} as any)
const AppBillingSuccessRoute = AppBillingSuccessRouteImport.update({
  id: "/billing/success",
  path: "/billing/success",
  getParentRoute: () => AppRoute,
} as any)
const AppCmsPagesIndexRoute = AppCmsPagesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppCmsPagesRoute,
} as any)
const AppCmsPagesPageIdRoute = AppCmsPagesPageIdRouteImport.update({
  id: "/$pageId",
  path: "/$pageId",
  getParentRoute: () => AppCmsPagesRoute,
} as any)
const AppCmsPagesCreateRoute = AppCmsPagesCreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => AppCmsPagesRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: "/settings/general",
  path: "/settings/general",
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: "/settings/notifications",
    path: "/settings/notifications",
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: "/settings/organization",
  path: "/settings/organization",
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: "/settings/security",
  path: "/settings/security",
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  "/404": typeof R404Route
  "/500": typeof R500Route
  "/": typeof AppIndexRoute
  "/complete-profile": typeof CompleteProfileRoute
  "/create-organization": typeof CreateOrganizationRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/loading-demo": typeof LoadingDemoRoute
  "/magic-link": typeof MagicLinkRouteWithChildren
  "/reset-password": typeof ResetPasswordRoute
  "/sign-in": typeof SignInRoute
  "/signup": typeof SignupRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/verify-email": typeof VerifyEmailRoute
  "/addons": typeof AppAddonsRouteWithChildren
  "/cms-pages": typeof AppCmsPagesRouteWithChildren
  "/team": typeof AppTeamRoute
  "/auth/callback": typeof AuthCallbackRoute
  "/invite/$token": typeof InviteTokenRoute
  "/magic-link/verify": typeof MagicLinkVerifyRoute
  "/magic-link/": typeof MagicLinkIndexRoute
  "/addons/$addonPath": typeof AppAddonsAddonPathRoute
  "/billing/failure": typeof AppBillingFailureRoute
  "/billing/success": typeof AppBillingSuccessRoute
  "/cms-pages/$pageId": typeof AppCmsPagesPageIdRoute
  "/cms-pages/create": typeof AppCmsPagesCreateRoute
  "/settings/general": typeof AppSettingsGeneralRoute
  "/settings/notifications": typeof AppSettingsNotificationsRoute
  "/settings/organization": typeof AppSettingsOrganizationRoute
  "/settings/security": typeof AppSettingsSecurityRoute
  "/billing/": typeof AppBillingIndexRoute
  "/cms-pages/": typeof AppCmsPagesIndexRoute
}
export interface FileRoutesByTo {
  "/404": typeof R404Route
  "/500": typeof R500Route
  "/complete-profile": typeof CompleteProfileRoute
  "/create-organization": typeof CreateOrganizationRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/loading-demo": typeof LoadingDemoRoute
  "/reset-password": typeof ResetPasswordRoute
  "/sign-in": typeof SignInRoute
  "/signup": typeof SignupRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/verify-email": typeof VerifyEmailRoute
  "/addons": typeof AppAddonsRouteWithChildren
  "/team": typeof AppTeamRoute
  "/auth/callback": typeof AuthCallbackRoute
  "/invite/$token": typeof InviteTokenRoute
  "/magic-link/verify": typeof MagicLinkVerifyRoute
  "/": typeof AppIndexRoute
  "/magic-link": typeof MagicLinkIndexRoute
  "/addons/$addonPath": typeof AppAddonsAddonPathRoute
  "/billing/failure": typeof AppBillingFailureRoute
  "/billing/success": typeof AppBillingSuccessRoute
  "/cms-pages/$pageId": typeof AppCmsPagesPageIdRoute
  "/cms-pages/create": typeof AppCmsPagesCreateRoute
  "/settings/general": typeof AppSettingsGeneralRoute
  "/settings/notifications": typeof AppSettingsNotificationsRoute
  "/settings/organization": typeof AppSettingsOrganizationRoute
  "/settings/security": typeof AppSettingsSecurityRoute
  "/billing": typeof AppBillingIndexRoute
  "/cms-pages": typeof AppCmsPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/404": typeof R404Route
  "/500": typeof R500Route
  "/_app": typeof AppRouteWithChildren
  "/complete-profile": typeof CompleteProfileRoute
  "/create-organization": typeof CreateOrganizationRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/loading-demo": typeof LoadingDemoRoute
  "/magic-link": typeof MagicLinkRouteWithChildren
  "/reset-password": typeof ResetPasswordRoute
  "/sign-in": typeof SignInRoute
  "/signup": typeof SignupRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/verify-email": typeof VerifyEmailRoute
  "/_app/addons": typeof AppAddonsRouteWithChildren
  "/_app/cms-pages": typeof AppCmsPagesRouteWithChildren
  "/_app/team": typeof AppTeamRoute
  "/auth/callback": typeof AuthCallbackRoute
  "/invite/$token": typeof InviteTokenRoute
  "/magic-link/verify": typeof MagicLinkVerifyRoute
  "/_app/": typeof AppIndexRoute
  "/magic-link/": typeof MagicLinkIndexRoute
  "/_app/addons/$addonPath": typeof AppAddonsAddonPathRoute
  "/_app/billing/failure": typeof AppBillingFailureRoute
  "/_app/billing/success": typeof AppBillingSuccessRoute
  "/_app/cms-pages/$pageId": typeof AppCmsPagesPageIdRoute
  "/_app/cms-pages/create": typeof AppCmsPagesCreateRoute
  "/_app/settings/general": typeof AppSettingsGeneralRoute
  "/_app/settings/notifications": typeof AppSettingsNotificationsRoute
  "/_app/settings/organization": typeof AppSettingsOrganizationRoute
  "/_app/settings/security": typeof AppSettingsSecurityRoute
  "/_app/billing/": typeof AppBillingIndexRoute
  "/_app/cms-pages/": typeof AppCmsPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/404"
    | "/500"
    | "/"
    | "/complete-profile"
    | "/create-organization"
    | "/forgot-password"
    | "/loading-demo"
    | "/magic-link"
    | "/reset-password"
    | "/sign-in"
    | "/signup"
    | "/unauthorized"
    | "/verify-email"
    | "/addons"
    | "/cms-pages"
    | "/team"
    | "/auth/callback"
    | "/invite/$token"
    | "/magic-link/verify"
    | "/magic-link/"
    | "/addons/$addonPath"
    | "/billing/failure"
    | "/billing/success"
    | "/cms-pages/$pageId"
    | "/cms-pages/create"
    | "/settings/general"
    | "/settings/notifications"
    | "/settings/organization"
    | "/settings/security"
    | "/billing/"
    | "/cms-pages/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/404"
    | "/500"
    | "/complete-profile"
    | "/create-organization"
    | "/forgot-password"
    | "/loading-demo"
    | "/reset-password"
    | "/sign-in"
    | "/signup"
    | "/unauthorized"
    | "/verify-email"
    | "/addons"
    | "/team"
    | "/auth/callback"
    | "/invite/$token"
    | "/magic-link/verify"
    | "/"
    | "/magic-link"
    | "/addons/$addonPath"
    | "/billing/failure"
    | "/billing/success"
    | "/cms-pages/$pageId"
    | "/cms-pages/create"
    | "/settings/general"
    | "/settings/notifications"
    | "/settings/organization"
    | "/settings/security"
    | "/billing"
    | "/cms-pages"
  id:
    | "__root__"
    | "/404"
    | "/500"
    | "/_app"
    | "/complete-profile"
    | "/create-organization"
    | "/forgot-password"
    | "/loading-demo"
    | "/magic-link"
    | "/reset-password"
    | "/sign-in"
    | "/signup"
    | "/unauthorized"
    | "/verify-email"
    | "/_app/addons"
    | "/_app/cms-pages"
    | "/_app/team"
    | "/auth/callback"
    | "/invite/$token"
    | "/magic-link/verify"
    | "/_app/"
    | "/magic-link/"
    | "/_app/addons/$addonPath"
    | "/_app/billing/failure"
    | "/_app/billing/success"
    | "/_app/cms-pages/$pageId"
    | "/_app/cms-pages/create"
    | "/_app/settings/general"
    | "/_app/settings/notifications"
    | "/_app/settings/organization"
    | "/_app/settings/security"
    | "/_app/billing/"
    | "/_app/cms-pages/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  AppRoute: typeof AppRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  CreateOrganizationRoute: typeof CreateOrganizationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoadingDemoRoute: typeof LoadingDemoRoute
  MagicLinkRoute: typeof MagicLinkRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/404": {
      id: "/404"
      path: "/404"
      fullPath: "/404"
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/500": {
      id: "/500"
      path: "/500"
      fullPath: "/500"
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/complete-profile": {
      id: "/complete-profile"
      path: "/complete-profile"
      fullPath: "/complete-profile"
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/create-organization": {
      id: "/create-organization"
      path: "/create-organization"
      fullPath: "/create-organization"
      preLoaderRoute: typeof CreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forgot-password": {
      id: "/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/loading-demo": {
      id: "/loading-demo"
      path: "/loading-demo"
      fullPath: "/loading-demo"
      preLoaderRoute: typeof LoadingDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/magic-link": {
      id: "/magic-link"
      path: "/magic-link"
      fullPath: "/magic-link"
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password": {
      id: "/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sign-in": {
      id: "/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/signup": {
      id: "/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/unauthorized": {
      id: "/unauthorized"
      path: "/unauthorized"
      fullPath: "/unauthorized"
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/verify-email": {
      id: "/verify-email"
      path: "/verify-email"
      fullPath: "/verify-email"
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/addons": {
      id: "/_app/addons"
      path: "/addons"
      fullPath: "/addons"
      preLoaderRoute: typeof AppAddonsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/cms-pages": {
      id: "/_app/cms-pages"
      path: "/cms-pages"
      fullPath: "/cms-pages"
      preLoaderRoute: typeof AppCmsPagesRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/team": {
      id: "/_app/team"
      path: "/team"
      fullPath: "/team"
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    "/auth/callback": {
      id: "/auth/callback"
      path: "/auth/callback"
      fullPath: "/auth/callback"
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/invite/$token": {
      id: "/invite/$token"
      path: "/invite/$token"
      fullPath: "/invite/$token"
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/magic-link/": {
      id: "/magic-link/"
      path: "/"
      fullPath: "/magic-link/"
      preLoaderRoute: typeof MagicLinkIndexRouteImport
      parentRoute: typeof MagicLinkRoute
    }
    "/magic-link/verify": {
      id: "/magic-link/verify"
      path: "/verify"
      fullPath: "/magic-link/verify"
      preLoaderRoute: typeof MagicLinkVerifyRouteImport
      parentRoute: typeof MagicLinkRoute
    }
    "/_app/addons/$addonPath": {
      id: "/_app/addons/$addonPath"
      path: "/$addonPath"
      fullPath: "/addons/$addonPath"
      preLoaderRoute: typeof AppAddonsAddonPathRouteImport
      parentRoute: typeof AppAddonsRoute
    }
    "/_app/billing/": {
      id: "/_app/billing/"
      path: "/billing"
      fullPath: "/billing/"
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/billing/failure": {
      id: "/_app/billing/failure"
      path: "/billing/failure"
      fullPath: "/billing/failure"
      preLoaderRoute: typeof AppBillingFailureRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/billing/success": {
      id: "/_app/billing/success"
      path: "/billing/success"
      fullPath: "/billing/success"
      preLoaderRoute: typeof AppBillingSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/cms-pages/": {
      id: "/_app/cms-pages/"
      path: "/"
      fullPath: "/cms-pages/"
      preLoaderRoute: typeof AppCmsPagesIndexRouteImport
      parentRoute: typeof AppCmsPagesRoute
    }
    "/_app/cms-pages/$pageId": {
      id: "/_app/cms-pages/$pageId"
      path: "/$pageId"
      fullPath: "/cms-pages/$pageId"
      preLoaderRoute: typeof AppCmsPagesPageIdRouteImport
      parentRoute: typeof AppCmsPagesRoute
    }
    "/_app/cms-pages/create": {
      id: "/_app/cms-pages/create"
      path: "/create"
      fullPath: "/cms-pages/create"
      preLoaderRoute: typeof AppCmsPagesCreateRouteImport
      parentRoute: typeof AppCmsPagesRoute
    }
    "/_app/settings/general": {
      id: "/_app/settings/general"
      path: "/settings/general"
      fullPath: "/settings/general"
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/settings/notifications": {
      id: "/_app/settings/notifications"
      path: "/settings/notifications"
      fullPath: "/settings/notifications"
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/settings/organization": {
      id: "/_app/settings/organization"
      path: "/settings/organization"
      fullPath: "/settings/organization"
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/settings/security": {
      id: "/_app/settings/security"
      path: "/settings/security"
      fullPath: "/settings/security"
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAddonsRouteChildren {
  AppAddonsAddonPathRoute: typeof AppAddonsAddonPathRoute
}

const AppAddonsRouteChildren: AppAddonsRouteChildren = {
  AppAddonsAddonPathRoute: AppAddonsAddonPathRoute,
}

const AppAddonsRouteWithChildren = AppAddonsRoute._addFileChildren(
  AppAddonsRouteChildren,
)

interface AppCmsPagesRouteChildren {
  AppCmsPagesPageIdRoute: typeof AppCmsPagesPageIdRoute
  AppCmsPagesCreateRoute: typeof AppCmsPagesCreateRoute
  AppCmsPagesIndexRoute: typeof AppCmsPagesIndexRoute
}

const AppCmsPagesRouteChildren: AppCmsPagesRouteChildren = {
  AppCmsPagesPageIdRoute: AppCmsPagesPageIdRoute,
  AppCmsPagesCreateRoute: AppCmsPagesCreateRoute,
  AppCmsPagesIndexRoute: AppCmsPagesIndexRoute,
}

const AppCmsPagesRouteWithChildren = AppCmsPagesRoute._addFileChildren(
  AppCmsPagesRouteChildren,
)

interface AppRouteChildren {
  AppAddonsRoute: typeof AppAddonsRouteWithChildren
  AppCmsPagesRoute: typeof AppCmsPagesRouteWithChildren
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBillingFailureRoute: typeof AppBillingFailureRoute
  AppBillingSuccessRoute: typeof AppBillingSuccessRoute
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddonsRoute: AppAddonsRouteWithChildren,
  AppCmsPagesRoute: AppCmsPagesRouteWithChildren,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppBillingFailureRoute: AppBillingFailureRoute,
  AppBillingSuccessRoute: AppBillingSuccessRoute,
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MagicLinkRouteChildren {
  MagicLinkVerifyRoute: typeof MagicLinkVerifyRoute
  MagicLinkIndexRoute: typeof MagicLinkIndexRoute
}

const MagicLinkRouteChildren: MagicLinkRouteChildren = {
  MagicLinkVerifyRoute: MagicLinkVerifyRoute,
  MagicLinkIndexRoute: MagicLinkIndexRoute,
}

const MagicLinkRouteWithChildren = MagicLinkRoute._addFileChildren(
  MagicLinkRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404Route,
  R500Route: R500Route,
  AppRoute: AppRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  CreateOrganizationRoute: CreateOrganizationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoadingDemoRoute: LoadingDemoRoute,
  MagicLinkRoute: MagicLinkRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
